import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import os

# Optional: pandas for reading connectivity CSV
try:
    import pandas as pd
    HAVE_PANDAS = True
except ImportError:
    HAVE_PANDAS = False

# Brian2 for spiking VNC network
try:
    import brian2 as b2
    BRIAN2_AVAILABLE = True
except ImportError:
    BRIAN2_AVAILABLE = False

"""
simulation.py

Kinematic C. elegans-like worm simulation (no axes, 2D container).
The worm is represented as a sinusoidal midline whose amplitude and
heading change over time, giving a noisy, slithering motion.

Run with:
    python simulation.py

If you need dependencies:
    python -m pip install numpy matplotlib
"""

# -----------------------------
# Global parameters
# -----------------------------

FPS = 30                    # frames per second (higher FPS, smoother motion)
DT = 1.0 / FPS              # time step in seconds

N_SEG = 40                  # number of points along the body (short, stubby worm)
BODY_LENGTH = 1.0           # total body length (arbitrary units, stubby worm)
WAVE_K = 0.25               # at most one gentle bend along the body
BASE_AMP = 0.05             # very small amplitude (barely undulating)
AMP_NOISE_GAIN = 0.10       # small variability
AMP_NOISE_DECAY = 0.9997    # extremely slow drift in bending amplitude

CPG_FREQ = 0.22             # slower, more biological undulation

# Propulsion in a resistive fluid: forward speed is generated by
# body undulations and scaled by this coefficient.
# Slightly higher coefficient and minimum speed effectively reduce
# "fluid resistance" so the worm translates faster.
FLUID_PROP_COEFF = 3.0      # stronger propulsion in fluid
MIN_FORWARD_SPEED = 0.025   # slightly higher forward floor

# Center-of-mass / head motion
MEAN_SPEED = 0.05           # slow crawling speed
SPEED_NOISE_GAIN = 0.18     # reduced variability
HEADING_DIFFUSION = np.deg2rad(8.0)   # small random drift of desired heading
TURN_RATE_LIMIT = np.deg2rad(70.0)    # max turn rate of actual heading (deg/s)
WALL_DETECT_MARGIN = 0.05             # early wall detection distance
WALL_AVOID_TIME = 1.0                 # seconds to keep steering away after a hit

# Curvature dynamics (controls how smoothly the head path bends)
CURVATURE_DECAY = 0.985                 # previous curvature persists longer
CURVATURE_NOISE_GAIN = np.deg2rad(2.0)  # smaller random curvature fluctuations
WALL_TURN_RATE = np.deg2rad(55.0)       # target curvature magnitude when avoiding a wall (rad/s)

# Container bounds (a simple box the worm lives in)
X_MIN, X_MAX = -2.5, 2.5
Y_MIN, Y_MAX = -1.5, 1.5

# Total duration of Brian2 VNC simulation (seconds of motor drive)
NETWORK_DURATION = 60.0

# Path to connectivity Excel file containing the real C. elegans connectivity.
# This should be the original spreadsheet in the project directory.
CONNECTIVITY_FILE = "CElegansNeuronConnections.xls"

# Placeholders for Brian2-generated motor drive (filled later)
network_A = None          # amplitude over time (from spikes)
network_curv = None       # curvature drive over time (from spikes)
network_len = 0           # number of samples
network_idx = 0           # current index into network arrays

# -----------------------------
# State variables
# -----------------------------

# Parameter along the body from head (0) to tail (1)
s = np.linspace(0.0, 1.0, N_SEG)

# Phase of the central pattern generator
phase = 0.0

# Smoothed random variable controlling amplitude variations
amp_noise_state = 0.0

# Heading angle of the worm (radians, 0 = positive x direction)
heading = 0.0

# Desired heading that the worm steers toward (for smooth turning)
target_heading = 0.0

# Timer indicating recent wall contact; during this time the worm prefers
# to keep steering away from the wall.
wall_avoid_timer = 0.0

# Curvature of the path (roughly, d(heading)/dt); used to ensure that
# the head direction changes smoothly over time (no teleporting angles).
curvature = 0.0

# Bias on curvature, mainly used for wall avoidance (steering away).
curvature_bias = 0.0

# Head position (x, y)
head_pos = np.array([0.0, 0.0], dtype=float)

# History of whole-body shapes so that the tail can trail behind
# the head with a realistic time lag.
MAX_HISTORY = N_SEG           # one frame of lag per segment
shape_history = np.zeros((MAX_HISTORY, N_SEG, 2), dtype=float)
history_idx = 0
history_filled = 0

# -----------------------------
# Helper functions
# -----------------------------


def _angle_diff(a, b):
    """
    Smallest signed difference from angle a to b (both radians),
    in the range [-pi, pi].
    """
    d = (b - a + np.pi) % (2.0 * np.pi) - np.pi
    return d

def _smooth_curve(x, y, passes=1):
    """
    Simple 1D smoothing along the body to remove sharp kinks due to
    discrete segment sampling or history lag. Applies a small
    [0.25, 0.5, 0.25] kernel along the segment index.
    """
    x_s = x.copy()
    y_s = y.copy()
    for _ in range(passes):
        x_pad = np.pad(x_s, (1, 1), mode="edge")
        y_pad = np.pad(y_s, (1, 1), mode="edge")
        x_s = 0.25 * x_pad[:-2] + 0.5 * x_pad[1:-1] + 0.25 * x_pad[2:]
        y_s = 0.25 * y_pad[:-2] + 0.5 * y_pad[1:-1] + 0.25 * y_pad[2:]
    return x_s, y_s

def build_vnc_motor_drive(total_time, dt_anim):
    """
    Build and run a Brian2 spiking network representing the ventral
    nerve cord (VNC) motor pools and convert its spike trains into
    time-series for body bending amplitude (A) and curvature drive.

    This version uses the original Excel connectivity file
    CElegansNeuronConnections.xls, which stores an edge list with
    columns:
        - 'Neuron 1'
        - 'Neuron 2'
        - 'Type' (e.g. chemical, EJ (gap junction), NMJ)

    We construct one LIF neuron per unique name in the spreadsheet,
    connect them according to the edge list, apply a sensory stimulus
    to specific modalities, and finally bin spikes into per-frame
    amplitude and curvature drives.

    If anything goes wrong (missing file, pandas not installed, etc.),
    we fall back to the simpler synthetic oscillator-based motor network.
    """
    if not BRIAN2_AVAILABLE:
        print("Brian2 not installed; falling back to kinematic drive.")
        return None, None

    # Use Brian2 units
    from brian2 import second, ms

    # Reset Brian2 state
    b2.start_scope()
    b2.defaultclock.dt = 0.1 * ms  # fine-grained network step, as in original test

    duration = total_time * second

    # -----------------------------
    # 1) Try to build network from real connectivity Excel file
    # -----------------------------
    use_connectome = False
    df = None

    if HAVE_PANDAS and os.path.exists(CONNECTIVITY_FILE):
        try:
            df = pd.read_excel(CONNECTIVITY_FILE)
            print(
                f"Building VNC network from edge-list connectivity file "
                f"'{CONNECTIVITY_FILE}' with {len(df)} edges."
            )
            use_connectome = True
        except Exception as e:
            print(
                f"Failed to load connectivity from '{CONNECTIVITY_FILE}': {e}\n"
                f"Falling back to synthetic motor network."
            )
            use_connectome = False
    else:
        if not HAVE_PANDAS:
            print("pandas not available; cannot read connectivity Excel file.")
        else:
            print(f"Connectivity file '{CONNECTIVITY_FILE}' not found.")
        use_connectome = False

    # -----------------------------
    # 1a) Connectome-based network (edge list)
    # -----------------------------
    if use_connectome and df is not None:
        # Build neuron index mapping from all names in 'Neuron 1' and 'Neuron 2'
        all_neurons = list(df['Neuron 1']) + list(df['Neuron 2'])
        neuron_dict = {}
        for name in all_neurons:
            if name not in neuron_dict:
                neuron_dict[name] = len(neuron_dict)

        NUM_NEURONS = len(neuron_dict)
        print(f"Unique neurons in connectome: {NUM_NEURONS}")

        # --- sensory modality groups (as in original test) ---
        # Names are treated as prefixes so they work with L/R variants
        touch_names   = ['ALM', 'AVM', 'PLM', 'PVM']
        stretch_names = ['DVA', 'PVD']
        chemo_names   = ['ASE', 'AWB', 'AWC']

        def find_matching_indices(prefixes):
            indices = []
            for name, idx in neuron_dict.items():
                for p in prefixes:
                    if p in name and idx not in indices:
                        indices.append(idx)
            return indices

        # modality indices
        touch_indices   = find_matching_indices(touch_names)
        stretch_indices = find_matching_indices(stretch_names)
        chemo_indices   = find_matching_indices(chemo_names)
        # more specific subsets for head vs tail touch
        head_touch_indices = find_matching_indices(['ALM', 'AVM'])
        tail_touch_indices = find_matching_indices(['PLM', 'PVM'])

        # Build lists of synaptic pairs by type
        neuron_pairs = [
            (neuron_dict[n1], neuron_dict[n2])
            for n1, n2 in zip(df['Neuron 1'], df['Neuron 2'])
        ]

        chemical = []
        gap_junctions = []

        # Use the 'Type' column to decide synapse type
        for idx_type, syn_type in enumerate(df['Type']):
            if idx_type >= len(neuron_pairs):
                break
            pre_idx, post_idx = neuron_pairs[idx_type]
            if syn_type == "EJ":
                gap_junctions.append((pre_idx, post_idx))
            elif syn_type != "NMJ":
                chemical.append((pre_idx, post_idx))

        # ---- Build Brian2 network ----
        from brian2 import NeuronGroup, Synapses, SpikeMonitor, network_operation

        tau = 10.0 * ms  # membrane time constant, as (I - v)/(10 ms)

        eqs = '''
        dv/dt = (I - v) / (10*ms) : 1
        I : 1
        '''

        neurons = NeuronGroup(
            NUM_NEURONS,
            eqs,
            threshold='v>0.2',
            reset='v=0',
            refractory=10*ms,
            method='exact'
        )
        neurons.v = 0
        baseline_I = 0.8
        neurons.I = baseline_I

        # stimulus configuration: choose which modality to stimulate
        # Options: 'touch_body', 'touch_head', 'touch_tail', 'stretch', 'chemo'
        stimulus_type = 'touch_body'

        @network_operation(dt=1*ms)
        def apply_stimulus(t):
            """
            Apply a time-varying input current I to selected sensory neurons.

            For a fraction of the total simulation time (roughly 10%–40%),
            neurons in the chosen modality group receive an increased input
            current. Outside this window, all neurons sit at the baseline
            current.
            """
            # reset to baseline each step
            neurons.I[:] = baseline_I

            # stimulus window scaled to total_time
            t_frac = t / duration  # dimensionless 0..1
            if 0.10 <= t_frac <= 0.40:
                if stimulus_type == 'touch_body':
                    neurons.I[touch_indices] = baseline_I + 0.5
                elif stimulus_type == 'touch_head':
                    neurons.I[head_touch_indices] = baseline_I + 0.5
                elif stimulus_type == 'touch_tail':
                    neurons.I[tail_touch_indices] = baseline_I + 0.5
                elif stimulus_type == 'stretch':
                    neurons.I[stretch_indices] = baseline_I + 0.5
                elif stimulus_type == 'chemo':
                    neurons.I[chemo_indices] = baseline_I + 0.5

        # excitatory chemical synapses
        chem_syn = Synapses(neurons, neurons, on_pre='v_post += 0.2')
        for pre, post in chemical:
            if pre is not None and post is not None:
                chem_syn.connect(i=pre, j=post)

        # electrical synapses (gap junctions)
        gap_syn = Synapses(
            neurons, neurons,
            model='w : 1',
            on_pre='v_post += w * (v_pre - v_post)'
        )
        for a, b in gap_junctions:
            if a is not None and b is not None:
                gap_syn.connect(i=a, j=b)
                gap_syn.connect(i=b, j=a)
        gap_syn.w = 0.05

        # record spikes for all neurons
        sm = SpikeMonitor(neurons)

        print(f"Running Brian2 connectome-based VNC for {total_time:.1f} s...")
        b2.run(duration)
        print("Brian2 connectome simulation finished.")

        # ---- Convert spikes to amplitude & curvature time series ----
        n_bins = int(np.floor(total_time / dt_anim))
        if n_bins <= 0:
            return None, None
        bin_edges = np.linspace(0.0, total_time, n_bins + 1)

        # Determine "left" vs "right" pools based on neuron names containing 'L' or 'R'.
        # If that fails, fall back to splitting the index set in half.
        left_indices = [
            idx for name, idx in neuron_dict.items()
            if 'L' in str(name)
        ]
        right_indices = [
            idx for name, idx in neuron_dict.items()
            if 'R' in str(name)
        ]
        if len(left_indices) == 0 or len(right_indices) == 0:
            # fallback: first half vs second half
            all_indices = list(range(NUM_NEURONS))
            half = max(1, NUM_NEURONS // 2)
            left_indices = all_indices[:half]
            right_indices = all_indices[half:]

        rate_L = np.zeros(n_bins)
        rate_R = np.zeros(n_bins)

        trains = sm.spike_trains()
        # Helper to accumulate rates from a given pool
        def accumulate_rates(indices, rate_arr):
            for idx in indices:
                if idx in trains:
                    t_i = (trains[idx] / second).astype(float)
                    counts, _ = np.histogram(t_i, bins=bin_edges)
                    rate_arr += counts

        accumulate_rates(left_indices, rate_L)
        accumulate_rates(right_indices, rate_R)

        bin_width = dt_anim
        # Normalize by number of neurons in each pool and bin width to get Hz
        rate_L = rate_L / (max(1, len(left_indices)) * bin_width)
        rate_R = rate_R / (max(1, len(right_indices)) * bin_width)

        total_rate = rate_L + rate_R
        baseline = np.median(total_rate)
        if baseline <= 0.0:
            baseline = 1.0

        # Amplitude: stronger total firing => slightly larger bending amplitude
        amp_norm = np.clip(total_rate / (2.0 * baseline), 0.0, 2.0)
        A_series = BASE_AMP * (0.5 + 0.5 * amp_norm)

        # Curvature drive: left-right imbalance maps to signed curvature
        diff_norm = np.clip((rate_L - rate_R) / baseline, -1.0, 1.0)
        max_curv = np.deg2rad(40.0)  # max curvature rate (rad/s)
        curvature_drive = max_curv * diff_norm

        return A_series, curvature_drive

    # -----------------------------
    # 2) Fallback: synthetic oscillator-based motor network
    # -----------------------------
    print("Using synthetic oscillator VNC (no connectivity Excel file).")

    from brian2 import NeuronGroup, Synapses, SpikeMonitor, Hz, pi, sin

    n_motor = 20  # motor neurons per side

    # Simple LIF-ish oscillator neurons with sinusoidal input
    tau = 20.0 * ms

    eqs = '''
    dv/dt = (-(v) + I0 + I1*sin(2*pi*f*t + phase))/tau : 1
    phase : 1
    I0    : 1
    I1    : 1
    f     : Hz
    '''

    G = NeuronGroup(2 * n_motor, eqs,
                    threshold='v>1', reset='v=0',
                    method='euler')

    # Base parameters for all neurons
    G.I0 = 0.7
    G.I1 = 0.6
    G.f = 0.7 * Hz

    # Left vs right motor pools with opposite phase
    G.phase[:n_motor] = 0.0          # "left" side
    G.phase[n_motor:] = np.pi        # "right" side, anti-phase

    # Monitors
    sm = SpikeMonitor(G)

    # Run the Brian2 network
    print("Running synthetic Brian2 VNC simulation for %.1f s..." % total_time)
    b2.run(duration)
    print("Brian2 synthetic simulation finished.")

    # Bin spikes into animation frames
    n_bins = int(np.floor(total_time / dt_anim))
    if n_bins <= 0:
        return None, None
    bin_edges = np.linspace(0.0, total_time, n_bins + 1)

    rate_L = np.zeros(n_bins)
    rate_R = np.zeros(n_bins)

    # Spike trains is a dict: index -> times
    trains = sm.spike_trains()
    for i in range(n_motor):
        t_i = (trains[i] / second).astype(float)
        counts, _ = np.histogram(t_i, bins=bin_edges)
        rate_L += counts
    for i in range(n_motor, 2 * n_motor):
        t_i = (trains[i] / second).astype(float)
        counts, _ = np.histogram(t_i, bins=bin_edges)
        rate_R += counts

    # Convert counts to firing rates in Hz (spikes / neuron / second)
    bin_width = dt_anim
    rate_L = rate_L / (n_motor * bin_width)
    rate_R = rate_R / (n_motor * bin_width)

    total_rate = rate_L + rate_R
    # Use median as a rough "baseline" to normalize
    baseline = np.median(total_rate)
    if baseline <= 0.0:
        baseline = 1.0

    # Amplitude: stronger total firing => slightly larger bending amplitude
    amp_norm = np.clip(total_rate / (2.0 * baseline), 0.0, 2.0)
    A_series = BASE_AMP * (0.5 + 0.5 * amp_norm)  # between 0.5*BASE_AMP and BASE_AMP

    # Curvature drive: left-right imbalance maps to signed curvature
    diff_norm = np.clip((rate_L - rate_R) / baseline, -1.0, 1.0)
    max_curv = np.deg2rad(40.0)  # max curvature rate (rad/s)
    curvature_drive = max_curv * diff_norm

    return A_series, curvature_drive

def update_brain(dt):
    """
    'Faux brain' that produces:
      - a central pattern generator phase
      - a slowly varying amplitude modulation
      - a smoothly changing heading that gently explores
        the environment and reacts to walls.

    The key idea here is that the head direction changes via a
    CURVATURE process: heading is the time integral of curvature,
    so the head path is always a smooth curve (no frame-to-frame
    teleporting in angle).
    """
    global phase, amp_noise_state, heading, wall_avoid_timer, head_pos
    global curvature, curvature_bias, network_idx

    # 1. CPG phase advance
    phase += 2.0 * np.pi * CPG_FREQ * dt

    if network_len > 0 and network_A is not None:
        # Use Brian2-generated motor drive
        idx = network_idx % network_len
        A = float(network_A[idx])
        curv_drive = float(network_curv[idx])
        network_idx = (network_idx + 1) % network_len
    else:
        # 2. Amplitude noise: AR(1) (smooth random fluctuations)
        amp_noise_state = AMP_NOISE_DECAY * amp_noise_state + \
                          (1.0 - AMP_NOISE_DECAY) * np.random.randn()
        amp_noise_state = np.clip(amp_noise_state, -1.5, 1.5)

        # Resulting amplitude
        A = BASE_AMP * (1.0 + AMP_NOISE_GAIN * amp_noise_state)
        A = max(0.05, A)  # never fully straight

        # Curvature drive from internal AR(1) process
        curv_drive = None

    # 3. Speed generated by undulation in a resistive fluid.
    #    Stronger bending (larger A) and faster CPG frequency lead to
    #    larger propulsion, scaled by FLUID_PROP_COEFF. We also enforce
    #    a small minimum forward speed so the worm clearly translates.
    base_speed = FLUID_PROP_COEFF * A * CPG_FREQ * BODY_LENGTH
    speed_scale = 1.0 + SPEED_NOISE_GAIN * np.random.randn()
    speed_scale = np.clip(speed_scale, 0.7, 1.3)
    speed = base_speed * speed_scale
    speed = max(MIN_FORWARD_SPEED, speed)  # always forward, never stuck

    # 4. Predict next head position using current heading
    step_preview = speed * dt * np.array([np.cos(heading), np.sin(heading)])
    preview_pos = head_pos + step_preview

    # 5. Wall "sensory" input: compute normal pointing away from nearby walls
    hit_wall = False
    normal = np.array([0.0, 0.0])
    if preview_pos[0] < X_MIN + WALL_DETECT_MARGIN:
        normal += np.array([1.0, 0.0])
        hit_wall = True
    elif preview_pos[0] > X_MAX - WALL_DETECT_MARGIN:
        normal += np.array([-1.0, 0.0])
        hit_wall = True
    if preview_pos[1] < Y_MIN + WALL_DETECT_MARGIN:
        normal += np.array([0.0, 1.0])
        hit_wall = True
    elif preview_pos[1] > Y_MAX - WALL_DETECT_MARGIN:
        normal += np.array([0.0, -1.0])
        hit_wall = True

    # Decrease avoidance timer
    wall_avoid_timer = max(0.0, wall_avoid_timer - dt)

    if hit_wall and np.linalg.norm(normal) > 0.0:
        # "Sensory" reaction: set a curvature bias that turns away from the wall
        away_angle = np.arctan2(normal[1], normal[0])
        angle_diff = _angle_diff(heading, away_angle)
        turn_sign = np.sign(angle_diff) if angle_diff != 0.0 else 0.0
        curvature_bias = turn_sign * WALL_TURN_RATE
        wall_avoid_timer = WALL_AVOID_TIME
    elif wall_avoid_timer <= 0.0:
        # When not avoiding a wall, slowly relax curvature bias back to 0
        curvature_bias *= 0.98

    if network_len > 0 and network_A is not None:
        # Directly use curvature drive from Brian2 network (no extra noise)
        curvature = curv_drive
    else:
        # 6. Update curvature: AR(1) toward curvature_bias + small noise
        curvature = (CURVATURE_DECAY * curvature +
                     (1.0 - CURVATURE_DECAY) * curvature_bias +
                     CURVATURE_NOISE_GAIN * np.random.randn())

    # 7. Integrate curvature to update heading smoothly
    heading_new = heading + curvature * dt

    # 8. Move head using the smoothly updated heading
    step = speed * dt * np.array([np.cos(heading_new), np.sin(heading_new)])
    new_head_pos = head_pos + step

    # 9. Hard clamp to keep the worm strictly inside bounds
    new_head_pos[0] = np.clip(new_head_pos[0], X_MIN + 0.1, X_MAX - 0.1)
    new_head_pos[1] = np.clip(new_head_pos[1], Y_MIN + 0.1, Y_MAX - 0.1)

    # Commit state
    heading = heading_new
    head_pos[:] = new_head_pos

    return A

def body_midline(A):
    """
    Compute the worm midline in world coordinates at the current phase,
    amplitude A, heading, and head_pos.

    We first compute an instantaneous traveling-wave body shape, then
    store it into a history buffer. The *rendered* worm uses a lagged
    version of this shape so that the tail literally follows the
    positions the more anterior segments had in previous frames. This
    makes the tail trail the head instead of mirroring its motion like
    a magnet.
    """
    global shape_history, history_idx, history_filled

    # 1. Instantaneous body shape in the worm frame
    # x_local: along the body from head (0) to tail (-BODY_LENGTH)
    x_local = -s * BODY_LENGTH

    # Very gentle change in amplitude from head to tail; the worm mostly
    # follows its path with a single broad bend, not a strong sinusoidal
    # wave along the body.
    amp_profile = 0.9 - 0.2 * s  # 0.9 at head, 0.7 at tail (almost uniform)
    local_phase = 2.0 * np.pi * (WAVE_K * s - phase)
    y_local = A * amp_profile * np.sin(local_phase)

    # Rotate into world frame
    c, si = np.cos(heading), np.sin(heading)
    x_rot = c * x_local - si * y_local
    y_rot = si * x_local + c * y_local

    # Translate to head position
    x_world = head_pos[0] + x_rot
    y_world = head_pos[1] + y_rot

    # 2. Store the instantaneous shape in the history buffer
    history_idx = (history_idx + 1) % MAX_HISTORY
    shape_history[history_idx, :, 0] = x_world
    shape_history[history_idx, :, 1] = y_world
    history_filled = min(history_filled + 1, MAX_HISTORY)

    # 3. Build a lagged shape where each segment index j uses a shape from
    #    an earlier frame. Segment 0 (head) is current; segment 1 is from
    #    1 frame ago; segment 2 from 2 frames ago; etc.
    if history_filled < MAX_HISTORY:
        # Not enough history yet; just use the instantaneous shape
        x_s, y_s = _smooth_curve(x_world, y_world, passes=2)
        return x_s, y_s

    x_out = np.empty_like(x_world)
    y_out = np.empty_like(y_world)
    for j in range(N_SEG):
        idx = (history_idx - j) % MAX_HISTORY
        x_out[j] = shape_history[idx, j, 0]
        y_out[j] = shape_history[idx, j, 1]

    x_s, y_s = _smooth_curve(x_out, y_out, passes=2)
    return x_s, y_s

# -----------------------------
# Build Brian2 network drive (if available)
# -----------------------------

if BRIAN2_AVAILABLE:
    network_A, network_curv = build_vnc_motor_drive(NETWORK_DURATION, DT)
    if network_A is not None and network_curv is not None:
        network_len = len(network_A)
        print("Using Brian2 VNC drive with %d samples." % network_len)
    else:
        print("Falling back to internal kinematic drive; Brian2 network not used.")
        network_len = 0
else:
    print("Brian2 not available; using internal kinematic drive.")

# -----------------------------
# Visualization setup
# -----------------------------

fig, ax = plt.subplots(figsize=(8, 4))

# Draw the worm as a thick line on a dark background
ax.set_facecolor("black")
line, = ax.plot([], [], lw=4, color="#5fd1ff")  # bluish worm
# Head marker (small nub at the head position)
head_marker, = ax.plot([], [], marker='o', markersize=6, color="#ffffff", zorder=5)
ax.set_xlim(X_MIN, X_MAX)
ax.set_ylim(Y_MIN, Y_MAX)
ax.set_aspect("equal")

# Hide all axes / ticks so it doesn't look like a graph
ax.set_xticks([])
ax.set_yticks([])
for spine in ax.spines.values():
    spine.set_visible(False)

fig.tight_layout()
fig.canvas.manager.set_window_title("C. elegans-like worm slithering")

def init():
    line.set_data([], [])
    head_marker.set_data([], [])
    return line, head_marker

def animate(frame):
    # Update the faux brain state and get new amplitude
    A = update_brain(DT)

    # Compute worm midline in world coordinates
    x, y = body_midline(A)
    line.set_data(x, y)

    # Place the head marker at the head (s = 0 -> index 0)
    if len(x) > 0:
        head_marker.set_data([x[0]], [y[0]])
    else:
        head_marker.set_data([], [])

    return line, head_marker

anim = FuncAnimation(
    fig,
    animate,
    init_func=init,
    frames=None,        # animate indefinitely
    interval=1000.0*DT, # milliseconds between frames (~30 FPS)
    blit=True
)

if __name__ == "__main__":
    plt.show()
